// ============================================================
//  Rise and Shine — Game Data Configuration
//  All character, byte, and level data lives here.
// ============================================================

window.GAME_DATA = {

  // ── Playable Characters ──────────────────────────────────
  characters: [
    {
      id: 'mj',
      name: 'MJ',
      role: 'Balanced Hero',
      roleDesc: 'A reliable all-around character. Good for beginners.',
      hp: 55,
      dmg: 18,
      passiveName: 'Fast Boot',
      passiveDesc: 'Starts every battle with +1 Byte special skill charge loaded.',
      image: 'playableCharacters/MJ/MJ_default.png',
    },
    {
      id: 'harold',
      name: 'Harold',
      role: 'Defensive Hero',
      roleDesc: 'A steady hero with higher Health, useful for surviving longer stages.',
      hp: 65,
      dmg: 14,
      passiveName: 'Guard Firewall',
      passiveDesc: 'Passive network shielding reduces all incoming enemy damage by 15%.',
      image: 'playableCharacters/Harold/Harold_default.png',
    },
    {
      id: 'bai',
      name: 'Bai',
      role: 'Damage Hero',
      roleDesc: 'A brave attacker with lower Health but stronger Damage.',
      hp: 48,
      dmg: 22,
      passiveName: 'Overclock Streak',
      passiveDesc: 'Deals +3 extra damage for each consecutive correct answer streak (caps at +9).',
      image: 'playableCharacters/Bai/Bai_default.png',
    },
    {
      id: 'dale',
      name: 'Dale',
      role: 'Hybrid Fighter',
      roleDesc: 'A strong and dependable fighter with solid Health and strong Damage.',
      hp: 60,
      dmg: 20,
      passiveName: 'Adrenaline Core',
      passiveDesc: 'When HP drops below 50%, Dale\'s core overclock increases Sync Power by +5.',
      image: 'playableCharacters/Dale/Dale_default.png',
    },
    {
      id: 'paps',
      name: 'Paps',
      role: 'Tank Hero',
      roleDesc: 'The highest-Health character, built for survival but lower Damage.',
      hp: 75,
      dmg: 12,
      passiveName: 'Auto-Repair Daemon',
      passiveDesc: 'Passively restores 3 HP at the end of every combat turn.',
      image: 'playableCharacters/Paps/Paps_default.png',
    },
    {
      id: 'bebz',
      name: 'Bebz',
      role: 'Stable Hero',
      roleDesc: 'A safe and consistent character with reliable stats.',
      hp: 58,
      dmg: 16,
      passiveName: 'Clean Data Flow',
      passiveDesc: 'Sync restores 5 HP to Bebz on every correct answer.',
      image: 'playableCharacters/Bebz/Bebz_default.png',
    },
    {
      id: 'matt',
      name: 'Matt',
      role: 'Power Attacker',
      roleDesc: 'The highest-Damage character, but with lower Health.',
      hp: 50,
      dmg: 24,
      passiveName: 'Critical Overload',
      passiveDesc: '25% chance to deal 1.5x damage on correct answers, but incorrect answers deal +2 self-damage.',
      image: 'playableCharacters/Matt/Matt_default.png',
    },
    {
      id: 'jb',
      name: 'JB',
      role: 'Survival Fighter',
      roleDesc: 'A durable hero with high Health and decent Damage for harder stages.',
      hp: 70,
      dmg: 15,
      passiveName: 'Recycle Protocol',
      passiveDesc: 'Instantly restores 8 HP to JB whenever a companion Byte\'s special skill is activated.',
      image: 'playableCharacters/JB/JB_default.png',
    },
  ],

  // Stat ceilings for bar scaling
  CHARACTER_MAX_HP: 75,
  CHARACTER_MAX_DMG: 24,

  // ── ALL Bytes (full registry for unlock panel) ───────────
  // unlockedAtStart: true means available from game start
  // unlockHint: shown on locked cards
  allBytes: [
    {
      id: 'pinglet',
      name: 'Pinglet',
      role: 'Network Scout Byte',
      roleDesc: 'Deals quick consistent damage and can reveal enemy weakness.',
      hp: 15,
      dmg: 15,
      skill: 'Ping Shot',
      skillEffect: 'Deals quick, consistent damage and can reveal enemy weakness.',
      backstory: "Originally created as a diagnostic tool for monitoring network latency, Pinglet's high-frequency acoustic pings evolved into a combat-ready sonar. It's incredibly fast and loves tracking down packet leaks and network abnormalities in the academy's infrastructure.",
      image: 'bytes/Pinglet/Pinglet_profile.png',
      cryCfg: { type: 'beep', freq: 660, duration: 0.3 },
      color: '#a78bfa',
      icon: '📡',
      unlockedAtStart: false,
      unlockHint: 'Clear Prelim Level 1 to unlock.',
    },
    {
      id: 'bitbug',
      name: 'Bitbug',
      role: 'Sneaky Byte',
      roleDesc: 'Deals damage and lowers enemy attack for one turn.',
      hp: 18,
      dmg: 16,
      skill: 'Code Sting',
      skillEffect: 'Deals damage and lowers enemy Damage by 20% for one turn. Perfect for weakening tough enemies.',
      backstory: "Born from a harmless compiler warning that refused to be resolved, Bitbug learned to survive by blending into deep code segments. It specializes in sneaky, surgical debugging strikes that leave systems temporarily running at reduced speed.",
      image: 'bytes/Bitbug/Bitbug_profile.png',
      cryCfg: { type: 'buzz', freq: 220, duration: 0.4 },
      color: '#34d399',
      icon: '🐛',
      unlockedAtStart: false,
      unlockHint: 'Clear Prelim Level 2 to unlock.',
    },
    {
      id: 'poturtle',
      name: 'Porturtle',
      role: 'Defensive Byte',
      roleDesc: 'Shields the team and absorbs punishment so you survive.',
      hp: 30,
      dmg: 10,
      skill: 'Port Shield',
      skillEffect: 'Reduces incoming damage by 40% for one enemy attack. Perfect for tanking the hardest hits in a pinch.',
      backstory: "Porturtle was designed to serve as a hardware firewall, defending server ports from overwhelming traffic surges. Over the years, its data-shell hardened with layers of military-grade encryption, making it the most resilient shield in the LUMEN network.",
      image: 'bytes/Poturtle/Porturtle_profile.png',
      cryCfg: { type: 'rumble', freq: 120, duration: 0.6 },
      color: '#4ade80',
      icon: '🛡',
      unlockedAtStart: true,
      unlockHint: 'One of your starter Bytes.',
    },
    {
      id: 'voltbyte',
      name: 'Voltbyte',
      role: 'Speed Attacker',
      roleDesc: 'Deals damage and may weaken the enemy\'s next attack.',
      hp: 18,
      dmg: 22,
      skill: 'Shock Strike',
      skillEffect: 'Deals damage and may weaken the enemy\'s next attack. Fast and unpredictable.',
      backstory: "Voltbyte is a hyperactive power-grid monitor that was struck by a rogue electrical surge during a mainframe overclocking event. It channels static electricity directly from the academy's power lines to stun and disrupt corrupted data streams.",
      image: null,  // no profile image yet — falls back to icon emoji
      cryCfg: { type: 'zap', freq: 1200, duration: 0.2 },
      color: '#fbbf24',
      icon: '⚡',
      unlockedAtStart: false,
      unlockHint: 'Clear Midterm Level 2 to unlock.',
    },
    {
      id: 'ramhorn',
      name: 'RAMhorn',
      role: 'Power Byte',
      roleDesc: 'Deals 2x Byte Damage to one enemy.',
      hp: 22,
      dmg: 20,
      skill: 'Memory Charge',
      skillEffect: 'Deals 2x Byte Damage to one enemy. Devastating when fully charged.',
      backstory: "RAMhorn was once a high-speed memory optimization routine. However, it grew stubborn and aggressive after being tasked with running bloated legacy database queries, transforming its buffer overflows into a powerful memory charge attack.",
      image: 'bytes/RAMHorn/RAMhorn_profile.png',
      cryCfg: { type: 'horn', freq: 80, duration: 0.7 },
      color: '#f87171',
      icon: '🔴',
      unlockedAtStart: false,
      unlockHint: 'Clear the Midterm Boss to unlock.',
    },
    {
      id: 'firewisp',
      name: 'Firewisp',
      role: 'Fire Spirit Byte',
      roleDesc: 'An offensive companion that burns enemies over time.',
      hp: 20,
      dmg: 18,
      skill: 'Flame Flicker',
      skillEffect: 'Deals damage and burns the enemy for two consecutive turns. Burn status stacks additional heat damage each round.',
      backstory: "Firewisp originated as a CPU thermal monitoring avatar that ran too hot. It learned to manipulate heat dissipation vents and firewalls, turning raw CPU thermal energy into sustained burning flames that scorch digital adversaries.",
      image: 'bytes/Firewisp/Firewisp_profile.png',
      cryCfg: { type: 'crackle', freq: 880, duration: 0.4 },
      color: '#f97316',
      icon: '🔥',
      unlockedAtStart: true,
      unlockHint: 'One of your starter Bytes.',
    },
    {
      id: 'keyfox',
      name: 'Keyfox',
      role: 'Security Byte',
      roleDesc: 'Deals damage and has a chance to lock the enemy\'s next attack.',
      hp: 22,
      dmg: 17,
      skill: 'Key Strike',
      skillEffect: 'Deals damage and has a chance to lock the enemy\'s next attack. Great for control.',
      backstory: "Keyfox was bred as a security verification daemon, designed to test password strengths and encryption locks. Stealthy and highly intelligent, it can instantly decrypt adversary security protocols and lock out incoming attacks.",
      image: null,  // no profile image yet — falls back to icon emoji
      cryCfg: { type: 'click', freq: 540, duration: 0.3 },
      color: '#facc15',
      icon: '🗝',
      unlockedAtStart: false,
      unlockHint: 'Clear the Prefinal Boss to unlock.',
    },
    {
      id: 'lagoon',
      name: 'Lagoon',
      role: 'Healing Byte',
      roleDesc: 'Keeps the team alive by restoring player health during battle.',
      hp: 25,
      dmg: 8,
      skill: 'Aqua Restore',
      skillEffect: 'Instantly restores 25 Health Points to the active player. Essential for surviving multi-level health carryover.',
      backstory: "Lagoon was developed as a cooling-system coolant flow visualizer. Known for its soothing, fluid dynamics-inspired interface, Lagoon channels pure, revitalizing data streams to cool down overheated circuits and heal damaged system code.",
      image: 'bytes/Lagoon/Lagoon_profile.png',
      cryCfg: { type: 'ripple', freq: 440, duration: 0.5 },
      color: '#38bdf8',
      icon: '💧',
      unlockedAtStart: true,
      unlockHint: 'One of your starter Bytes.',
    },
    {
      id: 'datashade',
      name: 'Datashade',
      role: 'Dark Data Byte',
      roleDesc: 'Deals damage and reduces the enemy\'s next attack power.',
      hp: 20,
      dmg: 19,
      skill: 'Shadow Packet',
      skillEffect: 'Deals damage and reduces the enemy\'s next attack power. Combination of offense and debuff.',
      backstory: "Formed in the dark, unallocated clusters of discarded hard drives, Datashade is a mysterious byte that manipulates shadow sectors and empty folders. It absorbs surrounding light and data packets to weaken adversarial output.",
      image: null,  // no profile image yet — falls back to icon emoji
      cryCfg: { type: 'dark', freq: 200, duration: 0.5 },
      color: '#818cf8',
      icon: '🌑',
      unlockedAtStart: false,
      unlockHint: 'Clear Final Level 4 to unlock.',
    },
    {
      id: 'glitchip',
      name: 'Glitchip',
      role: 'Random Effect Byte',
      roleDesc: 'Deals random damage between 15 and 35. Chaotic but powerful.',
      hp: 20,
      dmg: 18,
      skill: 'Error Pulse',
      skillEffect: 'Deals random damage between 15 and 35. The outcome is unpredictable — embrace the glitch!',
      backstory: "Glitchip is a fascinating anomaly—the result of a cosmic ray flipping a single bit in a random number generator chip. It embraces absolute chaos, outputting completely random damage numbers and unpredictable, glitched energy waves.",
      image: null,  // no profile image yet — falls back to icon emoji
      cryCfg: { type: 'glitch', freq: 440, duration: 0.3 },
      color: '#e879f9',
      icon: '🎲',
      unlockedAtStart: false,
      unlockHint: 'Special unlock — defeat a Stage Boss with full HP.',
    },
  ],

  BYTE_MAX_HP: 30,
  BYTE_MAX_DMG: 22,

  // ── Prelim Arc Levels ────────────────────────────────────
  prelimLevels: [
    {
      id: 1,
      name: 'Level 1',
      subtitle: 'Bit Mite',
      mapImage: 'scenes/PrelimMap/CorruptedClassroom_Prelim.png',
      enemy: 'Bit Mite',
      enemyHp: 130,
      enemyDmg: 12,
      enemyDesc: 'A tiny rogue data fragment that nibbles at your confidence. Very easy — perfect for learning the ropes.',
      enemyIdleSrc:   'glitchbornBytes/Bitmite/bitmite_idle.png',
      enemyAttackSrc: 'glitchbornBytes/Bitmite/Bitmite_attack.png',
      cutsceneEnemyLabel: 'BIT MITE',
      bgm: 'prelimStage',
      isBoss: false,
      challenges: [
        'Answer basic questions to chip away at the Bit Mite\'s 130 HP',
        'Wrong answers let it deal 12 DMG to you',
        '45s Question Timer is active (timeout deals damage)',
        'Health carries over to the next level',
      ],
      rewards: [
        'Clearance: Library Zone unlocked',
        'Pinglet Byte unlocked! 📡',
        'Combat mechanics tutorial complete',
      ],
      unlockOnClear: { nextLevel: 2, byteId: 'pinglet' },
      locked: false,
      position: { left: '19%', top: '66%' },
      useTutorialFlow: true,
      postCutsceneLines: [
        { speaker: 'player', text: 'It vanished into pixels.' },
        { speaker: 'byte',   text: 'Byte!' },
        { speaker: 'player', text: 'So the Glitchborn are corrupted Bytes made from broken learning data.' },
      ],
      questionsBank: [
        { q: 'What does IT stand for?', choices: { A: 'Information Technology', B: 'Internet Technology', C: 'Internal Tools', D: 'Integrated Teaching' }, answer: 'A' },
        { q: 'Which device is commonly used to input text into a computer?', choices: { A: 'Speaker', B: 'Monitor', C: 'Keyboard', D: 'Printer' }, answer: 'C' },
        { q: 'Which computer part displays visual output?', choices: { A: 'Scanner', B: 'Mouse', C: 'Keyboard', D: 'Monitor' }, answer: 'D' },
        { q: 'Which component is often called the brain of the computer?', choices: { A: 'CPU', B: 'Hard drive', C: 'Power supply', D: 'RAM' }, answer: 'A' },
        { q: 'Which type of memory is temporary and clears when the computer turns off?', choices: { A: 'HDD', B: 'SSD', C: 'RAM', D: 'ROM' }, answer: 'C' },
        { q: 'Which storage device is usually faster than a traditional hard disk drive?', choices: { A: 'DVD', B: 'Floppy disk', C: 'SSD', D: 'Printer' }, answer: 'C' },
        { q: 'What does OS stand for?', choices: { A: 'Online System', B: 'Output Service', C: 'Operating System', D: 'Open Software' }, answer: 'C' },
        { q: 'Which of the following is an operating system?', choices: { A: 'Windows', B: 'Adobe Photoshop', C: 'Google Chrome', D: 'Microsoft Word' }, answer: 'A' },
        { q: 'Which software is used to browse websites?', choices: { A: 'Database', B: 'Compiler', C: 'Web browser', D: 'Spreadsheet' }, answer: 'C' },
        { q: 'Which of these is an input device?', choices: { A: 'Printer', B: 'Mouse', C: 'Monitor', D: 'Speaker' }, answer: 'B' },
        { q: 'Which of these is an output device?', choices: { A: 'Scanner', B: 'Mouse', C: 'Keyboard', D: 'Printer' }, answer: 'D' },
        { q: 'What does GUI stand for?', choices: { A: 'General User Internet', B: 'Graphical User Interface', C: 'Graphic Unit Instruction', D: 'Global Utility Input' }, answer: 'B' },
        { q: 'Which number system uses only 0 and 1?', choices: { A: 'Binary', B: 'Decimal', C: 'Octal', D: 'Hexadecimal' }, answer: 'A' },
        { q: 'What is a bit?', choices: { A: 'The smallest unit of data', B: 'A computer screen', C: 'A group of files', D: 'A software update' }, answer: 'A' },
        { q: 'How many bits are in one byte?', choices: { A: '2', B: '16', C: '8', D: '4' }, answer: 'C' },
        { q: 'What is the physical connection port commonly used to connect a wired mouse or flash drive?', choices: { A: 'HDMI', B: 'USB', C: 'Ethernet', D: 'VGA' }, answer: 'B' },
        { q: 'What does HTML stand for?', choices: { A: 'Hypertext Markup Language', B: 'High Tech Modern Language', C: 'Hyperlink Text Management Logic', D: 'Home Tool Markup Line' }, answer: 'A' },
        { q: 'Which key is used to cancel or exit the current operation or close a menu popup?', choices: { A: 'Enter', B: 'Spacebar', C: 'Escape', D: 'Caps Lock' }, answer: 'C' },
        { q: 'What is the primary purpose of a computer network?', choices: { A: 'To increase monitor brightness', B: 'To share resources and information', C: 'To clean the keyboard', D: 'To charge the battery faster' }, answer: 'B' },
        { q: 'Which component contains the computer\'s motherboard, CPU, power supply, and storage drives?', choices: { A: 'Mouse', B: 'System Unit (Tower)', C: 'Keyboard', D: 'Printer' }, answer: 'B' },
      ],
    },
    {
      id: 2,
      name: 'Level 2',
      subtitle: 'Cache Slime',
      mapImage: 'scenes/PrelimMap/CorruptedClassroom_Prelim.png',
      enemy: 'Cache Slime',
      enemyHp: 180,
      enemyDmg: 14,
      enemyDesc: 'A memory-corrupted ooze that clings to misremembered data. It keeps multiplying like temporary memory overflowing.',
      enemyIdleSrc:   'glitchbornBytes/CacheSlime/CacheSlime_idle.png',
      enemyAttackSrc: 'glitchbornBytes/CacheSlime/CacheSlime_Attack.png',
      cutsceneEnemyLabel: 'CACHE SLIME',
      bgm: 'prelimStage',
      isBoss: false,
      challenges: [
        'Cache Slime has 180 HP and 14 DMG',
        '40s Question Timer is active (timeout deals damage)',
        'Memory and storage knowledge is tested here',
        'Your remaining HP carries over from Level 1',
      ],
      rewards: [
        'Clearance: Lab Zone unlocked',
        'Bitbug Byte unlocked! 🐛',
        'Level 3 path opens',
      ],
      unlockOnClear: { nextLevel: 3, byteId: 'bitbug' },
      locked: true,
      position: { left: '34%', top: '50%' },
      introCutsceneLines: [
        { speaker: 'system', text: 'Glitchborn Byte detected: Cache Slime.' },
        { speaker: 'player', text: 'That thing keeps dividing. It looks like temporary memory gone wrong.' },
      ],
      postCutsceneLines: [
        { speaker: 'player', text: 'It kept multiplying like an overload.' },
        { speaker: 'system', text: 'Prelim zone corruption reduced.' },
        { speaker: 'player', text: 'If we keep clearing them, maybe the classroom can be restored.' },
      ],
      questionsBank: [
        { q: 'Which file extension is commonly used for plain text files?', choices: { A: '.txt', B: '.jpg', C: '.exe', D: '.mp3' }, answer: 'A' },
        { q: 'Which file extension is commonly used for image files?', choices: { A: '.mp3', B: '.docx', C: '.xlsx', D: '.jpg' }, answer: 'D' },
        { q: 'What is hardware?', choices: { A: 'Computer instructions', B: 'Network password', C: 'Website content', D: 'Physical computer components' }, answer: 'D' },
        { q: 'What is software?', choices: { A: 'Physical computer parts', B: 'Internet cable', C: 'Programs and applications', D: 'Computer chair' }, answer: 'C' },
        { q: 'Which of these is system software?', choices: { A: 'Facebook', B: 'Canva', C: 'YouTube', D: 'Windows' }, answer: 'D' },
        { q: 'Which of these is application software?', choices: { A: 'BIOS', B: 'Microsoft Word', C: 'Operating system kernel', D: 'Device driver' }, answer: 'B' },
        { q: 'What does URL stand for?', choices: { A: 'Unified Routing Line', B: 'Universal Record Link', C: 'Uniform Resource Locator', D: 'User Reference Login' }, answer: 'C' },
        { q: 'What does HTTP mainly support?', choices: { A: 'Image editing', B: 'Computer cooling', C: 'Web communication', D: 'File compression' }, answer: 'C' },
        { q: 'What is the main purpose of antivirus software?', choices: { A: 'Protect against malware', B: 'Edit videos', C: 'Print documents', D: 'Speed up typing' }, answer: 'A' },
        { q: 'What is malware?', choices: { A: 'A storage device', B: 'A keyboard type', C: 'Malicious software', D: 'Helpful software' }, answer: 'C' },
        { q: 'Which of these is the strongest password example?', choices: { A: 'Mark123', B: '123456', C: 'M@rk!2026#IT', D: 'password' }, answer: 'C' },
        { q: 'What is phishing?', choices: { A: 'Catching fish online', B: 'Installing updates', C: 'A fake attempt to steal information', D: 'Creating backups' }, answer: 'C' },
        { q: 'What is a backup?', choices: { A: 'A deleted folder', B: 'A slow computer', C: 'A broken file', D: 'A copy of important data' }, answer: 'D' },
        { q: 'What does Wi-Fi allow devices to do?', choices: { A: 'Connect wirelessly to a network', B: 'Clean storage automatically', C: 'Print without ink', D: 'Increase battery capacity' }, answer: 'A' },
        { q: 'Which device commonly connects multiple devices to the internet?', choices: { A: 'Router', B: 'Monitor', C: 'Keyboard', D: 'Webcam' }, answer: 'A' },
        { q: 'Which action removes a file from its current location?', choices: { A: 'Refresh', B: 'Zoom', C: 'Delete', D: 'Minimize' }, answer: 'C' },
        { q: 'What is the Recycle Bin usually used for?', choices: { A: 'Running applications', B: 'Editing images', C: 'Scanning networks', D: 'Temporarily storing deleted files' }, answer: 'D' },
        { q: 'What is a shortcut icon?', choices: { A: 'A backup battery', B: 'A duplicate CPU', C: 'A link that opens a file, folder, or program', D: 'A network virus' }, answer: 'C' },
        { q: 'What is a file name extension used for?', choices: { A: 'Starting the router', B: 'Increasing memory', C: 'Identifying the file type', D: 'Changing the screen color' }, answer: 'C' },
        { q: 'Which extension is commonly used for Microsoft Word documents?', choices: { A: '.docx', B: '.mp4', C: '.html', D: '.exe' }, answer: 'A' },
        { q: 'Which extension is commonly used for spreadsheets?', choices: { A: '.png', B: '.wav', C: '.zip', D: '.xlsx' }, answer: 'D' },
        { q: 'Which extension is commonly used for compressed files?', choices: { A: '.zip', B: '.jpg', C: '.pptx', D: '.txt' }, answer: 'A' },
        { q: 'What is a browser tab used for?', choices: { A: 'Opening multiple pages in one browser window', B: 'Print faster', C: 'Creating passwords automatically', D: 'Installing RAM' }, answer: 'A' },
        { q: 'What should you do if you receive a suspicious link?', choices: { A: 'Enter your password immediately', B: 'Forward it to everyone', C: 'Disable antivirus', D: 'Avoid clicking it and verify the sender' }, answer: 'D' },
        { q: 'What is a computer virus?', choices: { A: 'A type of monitor', B: 'A keyboard setting', C: 'A useful update', D: 'Malware that can spread and damage systems' }, answer: 'D' },
        { q: 'What is the purpose of software updates?', choices: { A: 'Fix bugs and improve security or features', B: 'Delete all applications', C: 'Break the operating system', D: 'Make passwords public' }, answer: 'A' },
        { q: 'Which is safer on a public computer?', choices: { A: 'Leaving accounts open', B: 'Sharing login details', C: 'Logging out after use', D: 'Saving passwords in the browser' }, answer: 'C' },
        { q: 'What does copy do?', choices: { A: 'Prints content', B: 'Duplicates selected content to the clipboard', C: 'Turns off the device', D: 'Deletes content permanently' }, answer: 'B' },
        { q: 'What does paste do?', choices: { A: 'Creates a router', B: 'Places copied or cut content somewhere else', C: 'Formats the hard drive', D: 'Updates antivirus' }, answer: 'B' },
        { q: 'What does cut do?', choices: { A: 'Moves selected content to the clipboard', B: 'Locks the screen', C: 'Creates a backup automatically', D: 'Runs a virus scan' }, answer: 'A' },
        { q: 'Which keyboard shortcut commonly copies selected content?', choices: { A: 'Ctrl + V', B: 'Ctrl + X', C: 'Ctrl + Z', D: 'Ctrl + C' }, answer: 'D' },
        { q: 'Which keyboard shortcut commonly saves a file?', choices: { A: 'Ctrl + F', B: 'Ctrl + S', C: 'Ctrl + A', D: 'Ctrl + N' }, answer: 'B' },
      ],
    },
    {
      id: 3,
      name: 'Level 3',
      subtitle: 'Syntax Sprout',
      mapImage: 'scenes/PrelimMap/CorruptedClassroom_Prelim.png',
      enemy: 'Syntax Sprout',
      enemyHp: 240,
      enemyDmg: 16,
      enemyDesc: 'A broken-code entity formed from cascading syntax errors. Every wrong move makes it stronger.',
      enemyIdleSrc:   'glitchbornBytes/SyntaxSprout/syntaxsprout_idle.png',
      enemyAttackSrc: 'glitchbornBytes/SyntaxSprout/SyntaxSprout_attack.png',
      cutsceneEnemyLabel: 'SYNTAX SPROUT',
      bgm: 'prelimStage',
      isBoss: false,
      challenges: [
        'Syntax Sprout has 240 HP and 16 DMG',
        '35s Question Timer is active (timeout deals damage)',
        'Programming fundamentals tested here',
        'HP carries over from earlier levels',
      ],
      rewards: [
        'Clearance: Gym Zone unlocked',
        'Level 4 path opens',
      ],
      unlockOnClear: { nextLevel: 4 },
      locked: true,
      position: { left: '50%', top: '57%' },
      introCutsceneLines: [
        { speaker: 'system', text: 'Glitchborn Byte detected: Syntax Sprout.' },
        { speaker: 'player', text: 'Broken symbols everywhere. This one is definitely a coding error.' },
      ],
      postCutsceneLines: [
        { speaker: 'player', text: 'A small mistake can break the whole program.' },
        { speaker: 'system', text: 'Unknown transmission detected.' },
        { speaker: 'player', text: 'Who said that?' },
      ],
      questionsBank: [
        { q: 'What is programming?', choices: { A: 'Writing instructions for computers', B: 'Cleaning hardware', C: 'Designing posters', D: 'Browsing websites' }, answer: 'A' },
        { q: 'Which of these is a programming language?', choices: { A: 'Google', B: 'Windows', C: 'Python', D: 'HTML folder' }, answer: 'C' },
        { q: 'What is a variable in programming?', choices: { A: 'A network cable', B: 'A virus', C: 'A named storage location for data', D: 'A fixed computer part' }, answer: 'C' },
        { q: 'Which data type is used for whole numbers?', choices: { A: 'Boolean', B: 'Character', C: 'Integer', D: 'String' }, answer: 'C' },
        { q: 'Which data type stores true or false values?', choices: { A: 'Boolean', B: 'Float', C: 'Array', D: 'String' }, answer: 'A' },
        { q: 'What is a string?', choices: { A: 'Text data', B: 'A virus type', C: 'A monitor cable', D: 'A group of numbers only' }, answer: 'A' },
        { q: 'What symbol is commonly used for assignment in many languages?', choices: { A: '+', B: '?', C: '=', D: '#' }, answer: 'C' },
        { q: 'What is an algorithm?', choices: { A: 'A computer brand', B: 'A step-by-step solution to a problem', C: 'A keyboard shortcut', D: 'A broken file' }, answer: 'B' },
        { q: 'What is a flowchart?', choices: { A: 'A programming language', B: 'A visual representation of steps', C: 'A type of virus', D: 'A storage device' }, answer: 'B' },
        { q: 'Which flowchart symbol usually represents a decision?', choices: { A: 'Circle', B: 'Rectangle', C: 'Oval', D: 'Diamond' }, answer: 'D' },
        { q: 'Which flowchart symbol usually represents a process or action?', choices: { A: 'Oval', B: 'Diamond', C: 'Triangle', D: 'Rectangle' }, answer: 'D' },
        { q: 'What is debugging?', choices: { A: 'Installing games', B: 'Printing output', C: 'Removing computer dust', D: 'Finding and fixing errors in code' }, answer: 'D' },
        { q: 'What is syntax in programming?', choices: { A: 'Internet connection', B: 'Rules for writing code', C: 'File size', D: 'Computer speed' }, answer: 'B' },
        { q: 'What can happen when code has a syntax error?', choices: { A: 'The program may fail to run properly', B: 'It becomes faster', C: 'It fixes itself', D: 'It deletes the operating system' }, answer: 'A' },
        { q: 'Which statement is commonly used to make decisions in code?', choices: { A: 'print statement', B: 'variable', C: 'if statement', D: 'comment' }, answer: 'C' },
        { q: 'What is a loop used for?', choices: { A: 'Formatting a monitor', B: 'Repeating actions', C: 'Stopping electricity', D: 'Encrypting files only' }, answer: 'B' },
        { q: 'Which loop runs while a condition remains true?', choices: { A: 'input loop', B: 'print loop', C: 'if loop', D: 'while loop' }, answer: 'D' },
        { q: 'What is a comment in code?', choices: { A: 'A virus', B: 'A password', C: 'An error', D: 'Text ignored by the computer' }, answer: 'D' },
        { q: 'Why are comments useful?', choices: { A: 'They explain code', B: 'They slow down hardware', C: 'They make code unreadable', D: 'They delete bugs automatically' }, answer: 'A' },
        { q: 'What is the main goal of Information Technology?', choices: { A: 'Removing computers', B: 'Only playing games', C: 'Replacing all teachers', D: 'Using technology to manage and process information' }, answer: 'D' },
        { q: 'Which key is commonly used to confirm a command or move to the next line?', choices: { A: 'Caps Lock', B: 'Escape', C: 'Enter', D: 'Shift' }, answer: 'C' },
        { q: 'Which key is commonly used to type capital letters temporarily?', choices: { A: 'Delete', B: 'Shift', C: 'Ctrl', D: 'Tab' }, answer: 'B' },
        { q: 'What does CPU stand for?', choices: { A: 'Computer Power Utility', B: 'Central Program User', C: 'Control Panel Unit', D: 'Central Processing Unit' }, answer: 'D' },
        { q: 'What does RAM stand for?', choices: { A: 'Remote Access Machine', B: 'Run Application Module', C: 'Random Access Memory', D: 'Read All Memory' }, answer: 'C' },
        { q: 'What does ROM stand for?', choices: { A: 'Run-Only Mode', B: 'Random Output Machine', C: 'Read Online Module', D: 'Read-Only Memory' }, answer: 'D' },
        { q: 'Which component provides electricity to computer parts?', choices: { A: 'Power supply unit', B: 'Web browser', C: 'Mouse', D: 'Monitor stand' }, answer: 'A' },
        { q: 'Which component stores data permanently even after shutdown?', choices: { A: 'Clipboard', B: 'Cache only', C: 'Storage drive', D: 'RAM' }, answer: 'C' },
        { q: 'Which unit is larger?', choices: { A: 'Byte', B: 'Kilobyte', C: 'Megabyte', D: 'Terabyte' }, answer: 'D' },
        { q: 'What does USB commonly stand for?', choices: { A: 'Ultra Speed Button', B: 'Universal Serial Bus', C: 'User System Backup', D: 'Unified Storage Board' }, answer: 'B' },
        { q: 'Which port is commonly used for modern video and audio output?', choices: { A: 'USB-A only', B: 'Audio jack only', C: 'RJ45', D: 'HDMI' }, answer: 'D' },
        { q: 'What is the desktop in an operating system?', choices: { A: 'A password manager', B: 'A computer fan', C: 'A physical table', D: 'The main screen area where icons and windows appear' }, answer: 'D' },
        { q: 'What is a folder used for?', choices: { A: 'Changing internet speed', B: 'Cooling the CPU', C: 'Increasing screen brightness', D: 'Organizing files' }, answer: 'D' },
      ],
    },
    {
      id: 4,
      name: 'Level 4',
      subtitle: 'File Phantom',
      mapImage: 'scenes/PrelimMap/CorruptedClassroom_Prelim.png',
      enemy: 'File Phantom',
      enemyHp: 300,
      enemyDmg: 18,
      enemyDesc: 'A corrupted file spirit that flickers in and out of existence. Requires consistency and accuracy to defeat.',
      enemyIdleSrc:   'glitchbornBytes/FilePhantom/FilePhantom_Idle.png',
      enemyAttackSrc: 'glitchbornBytes/FilePhantom/FilePhantom_Attack.png',
      cutsceneEnemyLabel: 'FILE PHANTOM',
      bgm: 'prelimStage',
      isBoss: false,
      challenges: [
        'File Phantom has 300 HP and 18 DMG',
        '30s Question Timer is active (timeout deals damage)',
        'File management and OS knowledge tested',
        'HP carries over — stay sharp!',
      ],
      rewards: [
        'Clearance: Classroom Zone unlocked',
        'Boss Chamber path opens',
      ],
      unlockOnClear: { nextLevel: 5 },
      locked: true,
      position: { left: '66%', top: '45%' },
      introCutsceneLines: [
        { speaker: 'system', text: 'Glitchborn Byte detected: File Phantom.' },
        { speaker: 'player', text: 'A corrupted file enemy. Stay sharp, it keeps disappearing.' },
      ],
      postCutsceneLines: [
        { speaker: 'system', text: 'Prelim boss chamber unlocked.' },
        { speaker: 'player', text: 'That must be where the professor is.' },
        { speaker: 'byte',   text: 'Byte…' },
        { speaker: 'player', text: 'Don\'t worry. We made it this far.' },
      ],
      questionsBank: [
        { q: 'What is an array?', choices: { A: 'A single variable only', B: 'A network device', C: 'A type of malware', D: 'A collection of related values' }, answer: 'D' },
        { q: 'In many programming languages, array indexing starts at what number?', choices: { A: '10', B: '0', C: '1', D: '2' }, answer: 'B' },
        { q: 'What is a function?', choices: { A: 'A computer virus', B: 'A database table only', C: 'A reusable block of code', D: 'A network cable' }, answer: 'C' },
        { q: 'What is a parameter?', choices: { A: 'A storage device', B: 'A web browser', C: 'A value passed into a function', D: 'A file extension' }, answer: 'C' },
        { q: 'What does a return statement usually do?', choices: { A: 'Opens a browser', B: 'Deletes a variable', C: 'Stops the computer', D: 'Sends a value back from a function' }, answer: 'D' },
        { q: 'What is object-oriented programming mainly based on?', choices: { A: 'Printers and scanners', B: 'Cables and routers', C: 'Objects and classes', D: 'Files and folders' }, answer: 'C' },
        { q: 'What is a class?', choices: { A: 'A hardware component', B: 'A blueprint for objects', C: 'A database password', D: 'An internet provider' }, answer: 'B' },
        { q: 'What is an object?', choices: { A: 'A network address', B: 'A broken file', C: 'A compiler error', D: 'An instance of a class' }, answer: 'D' },
        { q: 'What is encapsulation?', choices: { A: 'Copying files', B: 'Connecting Wi-Fi', C: 'Printing output', D: 'Hiding data and exposing controlled access' }, answer: 'D' },
        { q: 'What is inheritance in OOP?', choices: { A: 'One class acquiring properties from another', B: 'Restarting software', C: 'Encrypting a file', D: 'Deleting a class' }, answer: 'A' },
        { q: 'What is polymorphism?', choices: { A: 'A database backup', B: 'The same interface having different behaviors', C: 'One password for all accounts', D: 'A virus mutation only' }, answer: 'B' },
        { q: 'What does IDE stand for?', choices: { A: 'Internal Design Engine', B: 'Internet Data Exchange', C: 'Integrated Development Environment', D: 'Input Device Editor' }, answer: 'C' },
        { q: 'Which tool converts source code into machine-readable code?', choices: { A: 'Monitor', B: 'Compiler', C: 'Router', D: 'Spreadsheet' }, answer: 'B' },
        { q: 'What is pseudocode?', choices: { A: 'Human-readable planning logic for a program', B: 'Machine language only', C: 'A virus code', D: 'A database record' }, answer: 'A' },
        { q: 'What is a nested loop?', choices: { A: 'A loop that never runs', B: 'A database backup', C: 'A loop placed inside another loop', D: 'A variable without value' }, answer: 'C' },
        { q: 'What is an infinite loop?', choices: { A: 'A loop that runs once', B: 'A loop that continues without stopping unless interrupted', C: 'A function that returns zero', D: 'A network command' }, answer: 'B' },
        { q: 'Which operator is commonly used for equality comparison in many languages?', choices: { A: '=', B: '+=', C: '==', D: '//' }, answer: 'C' },
        { q: 'Which operator commonly means AND in many programming languages?', choices: { A: '||', B: '&&', C: '!=', D: '++' }, answer: 'B' },
        { q: 'Which operator commonly means OR in many programming languages?', choices: { A: '||', B: '&&', C: '==', D: '--' }, answer: 'A' },
        { q: 'What is concatenation?', choices: { A: 'Joining strings together', B: 'Compiling code', C: 'Creating a table key', D: 'Deleting arrays' }, answer: 'A' },
        { q: 'What is type casting?', choices: { A: 'Converting a value from one data type to another', B: 'Making variables private', C: 'Deleting data types', D: 'Resetting a router' }, answer: 'A' },
        { q: 'What is recursion?', choices: { A: 'A CSS rule repeating itself', B: 'A database table joining itself only', C: 'A router restarting itself', D: 'A function calling itself' }, answer: 'D' },
        { q: 'What is a stack data structure based on?', choices: { A: 'Shortest job first', B: 'First In, First Out', C: 'Random access only', D: 'Last In, First Out' }, answer: 'D' },
        { q: 'What is a queue data structure based on?', choices: { A: 'Highest score first', B: 'Smallest data first', C: 'First In, First Out', D: 'Last In, First Out' }, answer: 'C' },
        { q: 'What is a linked list?', choices: { A: 'A list of websites only', B: 'A CSS class list', C: 'A sequence of nodes connected by references', D: 'A database password list' }, answer: 'C' },
        { q: 'What is a syntax error?', choices: { A: 'An error caused by breaking language rules', B: 'A storage capacity issue', C: 'A design color issue', D: 'An error caused by slow internet' }, answer: 'A' },
        { q: 'What is a runtime error?', choices: { A: 'An error before code is written', B: 'A planned output', C: 'An error that occurs while the program is running', D: 'A router configuration' }, answer: 'C' },
        { q: 'What is a logic error?', choices: { A: 'Computer will not turn on', B: 'Code runs but produces an incorrect result', C: 'Code cannot compile due to punctuation', D: 'A monitor display issue' }, answer: 'B' },
        { q: 'What is an exception?', choices: { A: 'A guaranteed correct output', B: 'A CSS property', C: 'A file extension', D: 'An unusual condition that interrupts normal program flow' }, answer: 'D' },
        { q: 'What is exception handling used for?', choices: { A: 'Changing hardware speed', B: 'Hiding all bugs forever', C: 'Deleting the database', D: 'Managing errors without crashing unexpectedly' }, answer: 'D' },
        { q: 'Which block is commonly used to handle exceptions?', choices: { A: 'if-only', B: 'try-catch', C: 'loop-loop', D: 'select-from' }, answer: 'B' },
        { q: 'Which keyboard shortcut commonly pastes copied content?', choices: { A: 'Ctrl + P', B: 'Ctrl + C', C: 'Ctrl + S', D: 'Ctrl + V' }, answer: 'D' },
      ],
    },
    {
      id: 5,
      name: 'Level 5',
      subtitle: 'Overclocked Ms.K',
      mapImage: 'scenes/PrelimMap/CorruptedClassroom_Prelim.png',
      enemy: 'Overclocked Ms.K',
      enemyHp: 450,
      enemyDmg: 24,
      enemyDesc: 'The first stage boss. Driven by perfectionism and stress, this professor tests your foundational knowledge to its limit.',
      enemyIdleSrc:   'stageBosses/PrelimBoss/idle_sprites/Ms.K_idle.png',
      enemyAttackSrc: 'stageBosses/PrelimBoss/attack_sprites/Ms.K_attack.png',
      enemyProfileSrc:'stageBosses/PrelimBoss/Ms.K_profile.png',
      cutsceneEnemyLabel: 'OVERCLOCKED MS.K',
      bgm: 'prelimBoss',
      isBoss: true,
      challenges: [
        'The Prelim Boss has 450 HP and 24 DMG',
        '25s Question Timer is active (timeout deals damage)',
        'Enter with whatever HP you have remaining',
        'Byte Skills are crucial — use them wisely',
      ],
      rewards: [
        'Prelim Arc CLEARED! 🎉',
        '+20 Max Health permanently on first clear',
        'Full HP restored after clearing the boss',
      ],
      unlockOnClear: { bossClear: true },
      locked: true,
      position: { left: '81%', top: '30%' },
      introCutsceneLines: [
        { speaker: 'boss',   text: 'Basics are everything.' },
        { speaker: 'boss',   text: 'If you cannot answer simple questions, you do not deserve to proceed.' },
        { speaker: 'player', text: 'Professor, this isn\'t you. The LUMEN Network corrupted you.' },
        { speaker: 'boss',   text: 'Incorrect. The only path forward is through endless assessment.' },
        { speaker: 'player', text: 'Then we\'ll answer, fight, and bring you back.' },
      ],
      postCutsceneLines: [
        { speaker: 'system', text: 'Prelim Arc restored. Professor freed from corruption.' },
        { speaker: 'player', text: 'Professor, the Glitchbell turned you into a boss.' },
        { speaker: 'boss',   text: 'I remember the bell. Then pressure… data… questions repeating endlessly.' },
        { speaker: 'boss',   text: 'Prelim was only the beginning. The academy has been divided into corrupted academic zones.' },
        { speaker: 'player', text: 'How do we fix it?' },
        { speaker: 'boss',   text: 'Keep moving forward. The hidden system at the center of LUMEN awaits.' },
        { speaker: 'system', text: 'Prelim Arc restored. Midterm path unlocked.' },
        { speaker: 'player', text: 'One stage down. We keep going.' },
      ],
      questionsBank: [
        { q: 'What is a database?', choices: { A: 'An organized collection of data', B: 'A computer monitor', C: 'A programming error', D: 'A network port' }, answer: 'A' },
        { q: 'What does DBMS stand for?', choices: { A: 'Direct Boot Memory Storage', B: 'Database Management System', C: 'Data Binary Machine Software', D: 'Digital Backup Main Server' }, answer: 'B' },
        { q: 'Which is an example of a DBMS?', choices: { A: 'Photoshop', B: 'VLC', C: 'MySQL', D: 'PowerPoint' }, answer: 'C' },
        { q: 'What is a table in a database?', choices: { A: 'A network wire', B: 'A physical desk', C: 'A password file', D: 'A structure of rows and columns' }, answer: 'D' },
        { q: 'What is a row in a database table also called?', choices: { A: 'Field', B: 'Record', C: 'Key only', D: 'Query language' }, answer: 'B' },
        { q: 'What is a column in a database table also called?', choices: { A: 'Backup', B: 'Database', C: 'Record', D: 'Field' }, answer: 'D' },
        { q: 'What is a primary key?', choices: { A: 'A duplicate field', B: 'A unique identifier for a record', C: 'A Wi-Fi password', D: 'A backup file' }, answer: 'B' },
        { q: 'What is a foreign key?', choices: { A: 'A hardware lock', B: 'A key that links one table to another', C: 'A deleted record', D: 'A password from another country' }, answer: 'B' },
        { q: 'Which SQL command retrieves data?', choices: { A: 'DELETE', B: 'FORMAT', C: 'DROP', D: 'SELECT' }, answer: 'D' },
        { q: 'Which SQL command adds new data?', choices: { A: 'UPDATE', B: 'SELECT', C: 'JOIN', D: 'INSERT' }, answer: 'D' },
        { q: 'Which SQL command modifies existing data?', choices: { A: 'SELECT', B: 'UPDATE', C: 'CREATE', D: 'BACKUP' }, answer: 'B' },
        { q: 'Which SQL command removes records?', choices: { A: 'RETURN', B: 'PRINT', C: 'DELETE', D: 'INPUT' }, answer: 'C' },
        { q: 'What does WHERE do in SQL?', choices: { A: 'Deletes the database', B: 'Filters records based on a condition', C: 'Creates a new server', D: 'Changes the OS' }, answer: 'B' },
        { q: 'What is normalization?', choices: { A: 'Making data more duplicated', B: 'Encrypting passwords only', C: 'Organizing data to reduce redundancy', D: 'Formatting a computer' }, answer: 'C' },
        { q: 'What is redundancy in databases?', choices: { A: 'Missing keyboard keys', B: 'Secure encryption', C: 'Unnecessary repetition of data', D: 'Faster internet' }, answer: 'C' },
        { q: 'What does LAN stand for?', choices: { A: 'Local Area Network', B: 'Large Access Node', C: 'Logical Application Number', D: 'Linked Account Name' }, answer: 'A' },
        { q: 'What does WAN stand for?', choices: { A: 'Wireless Access Number', B: 'Wide Area Network', C: 'Wired Account Network', D: 'Web Application Node' }, answer: 'B' },
        { q: 'Which device forwards data packets between networks?', choices: { A: 'Printer', B: 'Router', C: 'Speaker', D: 'Keyboard' }, answer: 'B' },
        { q: 'Which device connects devices within the same local network?', choices: { A: 'Scanner', B: 'Switch', C: 'Monitor', D: 'Mouse' }, answer: 'B' },
        { q: 'What is an IP address?', choices: { A: 'A unique address for a device on a network', B: 'A type of printer', C: 'A programming loop', D: 'A file name' }, answer: 'A' },
        { q: 'What does DNS do?', choices: { A: 'Compiles code', B: 'Translates domain names into IP addresses', C: 'Deletes malware', D: 'Stores passwords only' }, answer: 'B' },
        { q: 'What does HTML stand for?', choices: { A: 'HyperText Markup Language', B: 'Hyperlink Text Machine Link', C: 'Home Tool Markup List', D: 'High Transfer Machine Logic' }, answer: 'A' },
        { q: 'What is HTML mainly used for?', choices: { A: 'Password cracking', B: 'Styling only', C: 'Database backup', D: 'Structuring web content' }, answer: 'D' },
        { q: 'What is CSS mainly used for?', choices: { A: 'Managing RAM', B: 'Writing SQL queries only', C: 'Creating routers', D: 'Styling web pages' }, answer: 'D' },
        { q: 'What is JavaScript mainly used for in web development?', choices: { A: 'Adding interactivity', B: 'Installing OS', C: 'Creating hardware', D: 'Replacing all databases' }, answer: 'A' },
        { q: 'Which HTML tag is used for a paragraph?', choices: { A: '<body>', B: '<br>', C: '<p>', D: '<h1>' }, answer: 'C' },
        { q: 'Which HTML tag creates a hyperlink?', choices: { A: '<link>', B: '<href>', C: '<a>', D: '<url>' }, answer: 'C' },
        { q: 'Which CSS property changes text color?', choices: { A: 'font-size', B: 'color', C: 'margin', D: 'background' }, answer: 'B' },
        { q: 'Which CSS property controls space outside an element?', choices: { A: 'border', B: 'display', C: 'padding', D: 'margin' }, answer: 'D' },
        { q: 'Which CSS property controls space inside an element?', choices: { A: 'width', B: 'position', C: 'margin', D: 'padding' }, answer: 'D' },
        { q: 'What is responsive design?', choices: { A: 'A database method', B: 'Design that only works on desktop', C: 'A virus defense', D: 'Design that adapts to different screen sizes' }, answer: 'D' },
        { q: 'What is Git used for?', choices: { A: 'Internet browsing', B: 'Version control', C: 'Video editing', D: 'Hardware repair' }, answer: 'B' },
      ],
    },
  ],
};

// Lock GAME_DATA to prevent unauthorized modifications
Object.freeze(window.GAME_DATA);
